// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Superheroes_Managment.Context;

#nullable disable

namespace Superheroes_Managment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Superheroes_Managment.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Heroes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alias = "The Dark Knight",
                            Name = "Batman"
                        },
                        new
                        {
                            Id = 2,
                            Alias = "Friendly Neighbor",
                            Name = "Spider-Man"
                        },
                        new
                        {
                            Id = 3,
                            Alias = "The Fastest Man",
                            Name = "Flash"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Green Lantern"
                        },
                        new
                        {
                            Id = 5,
                            Alias = "God of Thunder",
                            Name = "Thor"
                        },
                        new
                        {
                            Id = 6,
                            Alias = "The First Avenger",
                            Name = "Captain America"
                        });
                });

            modelBuilder.Entity("Superheroes_Managment.Models.Power", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("Powers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Exceptional deduction",
                            HeroId = 1,
                            Name = "Detective Skills"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Hand-to-hand combat",
                            HeroId = 1,
                            Name = "Martial Arts"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Alerts to danger",
                            HeroId = 2,
                            Name = "Spider Sense"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Spins spider webs",
                            HeroId = 2,
                            Name = "Web-Shooting"
                        });
                });

            modelBuilder.Entity("Superheroes_Managment.Models.Power", b =>
                {
                    b.HasOne("Superheroes_Managment.Models.Hero", "Hero")
                        .WithMany()
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });
#pragma warning restore 612, 618
        }
    }
}
